# Default values for cosmere-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: mazigros/cosmereapi
  pullPolicy: Always
  tag: "latest"

nameOverride: "cosmere-api"
fullnameOverride: "cosmere-api"

app:
  port: 8080

service:
  name: cosmere-service
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  name: cosmere-ingress
  className: "nginx"
  annotations: { nginx.ingress.kubernetes.io/rewrite-target: / }
  hosts:
    - host: cosmere-api.com
      paths:
        - path: /
          pathType: ImplementationSpecific
